import type { Metadata } from "next";
import { Geist_Mono, Playfair_Display, Inter } from "next/font/google";
import "./globals.css";

import { AOSInit } from "@/components/AOSInit";
import { FloatingButtons } from "@/components/ui/FloatingButtons";
import { LanguageProvider } from "@/components/providers/LanguageProvider";



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${playfair.variable} ${geistMono.variable} font-sans antialiased overflow-x-hidden`}
      >
        <LanguageProvider>
          <AOSInit />
          <FloatingButtons />
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}
